### PR TITLE
Read script from slave node instead of master

### LINKED ISSUE #19: Impossible to use a groovy script in a slave node workspace
I use Jenkins 2.107.2 and Matrix Groovy Execution Strategy Plugin 1.07.

It's impossible to use workspace groovy script configuration when the job is executed on a slave node.

The job is a multi-configuration project, and its execution is restricted on a slave node.

If I execute the job on the master node, it's work, the plugin gets the script in the workspace, but it fails when it's executed on a slave node.

```

Started by timer
[EnvInject] - Loading node environment variables.
Building remotely on slave2 in workspace /jenkins/workspace/Test_auto
Updating svn://svnserver/validation at revision '2018-10-25T15:03:00.356 +0200'
At revision 12933

No changes for svn://svnserver/validation since the previous build
FATAL: /jenkins/workspace/Test_auto/slave_configuration.gy (No such file or directory)
java.io.FileNotFoundException: /jenkins/workspace/Test_auto/slave_configuration.gy (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at sun.reflect.GeneratedConstructorAccessor891.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at org.jenkinsci.plugins.WorkspaceFileReader.<init>(WorkspaceFileReader.groovy:25)
	at sun.reflect.GeneratedConstructorAccessor887.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at org.jenkinsci.plugins.GroovyScriptMES.decideOrder(GroovyScriptMES.groovy:54)
	at org.jenkinsci.plugins.GroovyScriptMES$decideOrder.callCurrent(Unknown Source)
	at org.jenkinsci.plugins.BaseMES.run(BaseMES.groovy:51)
	at hudson.matrix.MatrixBuild$MatrixBuildExecution.doRun(MatrixBuild.java:375)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1727)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE

```

### PR DESCRIPTION
**Pull request by lupalby**
Fixes #19 
I am not familiar with Jenkins plugin development, but from what I have read in the documentation we cannot use `File` to read a file that is potentially on a node different from master/built-in, where the plugin is running. The proper way is to use `FilePath`. I tried to simply read the text from the remote file and pass it around, to keep the rest of the plugin as simple as possible.
I did not have a chance to test it because I don't have anything setup to do so, I would kindly ask anybody with more experience to look at the very simple changes I made and give them a try if they make sense.

### CODE REVIEW

**Comment by lupalby** [comment]
Hi @JeremyMarshall thank you so much for your plugin, I found it extremely helpful. Any chance we could take a look at my change? If you're not involved in this plugin anymore, who else could give a look to it to move it forward?

**Comment by JeremyMarshall** [comment]
I'm not sure of the way to release plugins anymore. I'm happy to merge and see what happens

I think Ir will need the binaries pushing (but not sure) This PR needs the version bumping first https://github.com/jenkinsci/matrix-groovy-execution-strategy-plugin/blob/master/build.gradle#L40)

**Comment by lupalby** [comment]
I have never run my change, so I don't want to merge without knowing if it will break everything or not. Do you have any way to test it?

**Comment by lupalby** [comment]
Actually, could you tell me how to build the plugin? Then I can deploy it in our jenkins to test it and if it works we can try to merge it

**Comment by lupalby** [comment]
@JeremyMarshall I was able to build locally finding some online example and I deployed it to our Jenkins. It works!! We can merge the PR.
PS: sorry for the multiple force-push, I was just trying to clean up the history

**Comment by lupalby** [comment]
@JeremyMarshall any chance we can merge this?

**Review by JeremyMarshall — APPROVED** [review]

**Pull request merged**
